# Generated by Django 5.2.7 on 2025-10-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('student_id', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
